<a href="https://colab.research.google.com/github/beingshub02/Deep-Learning-Summer-School-IIITDM/blob/main/25DLS455.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 P-1: Create a softmax function [2.5 Marks]

In [ ]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x - np.max(x))  # for numerical stability
    return exp_x / np.sum(exp_x)

# Test Case
x = np.array([1.0, 2.0, 3.0])
print("Softmax Output:", softmax(x))


Softmax Output: [0.09003057 0.24472847 0.66524096]


 P-2: Identify Which Problem is Which? [2.5 Marks]

In [ ]:
examples = [
    "Self-driving car using CNNs",
    "Spam detection using Naive Bayes",
    "Expert system for medical diagnosis",
    "Face recognition using Siamese Networks",
    "Weather forecasting using linear regression"
]

for example in examples:
    if "CNNs" in example or "Siamese Networks" in example:
        print(f"{example} => DL (Deep Learning)")
    elif "Naive Bayes" in example or "linear regression" in example:
        print(f"{example} => ML (Machine Learning)")
    elif "Expert system" in example:
        print(f"{example} => AI (Artificial Intelligence)")


Self-driving car using CNNs => DL (Deep Learning)
Spam detection using Naive Bayes => ML (Machine Learning)
Expert system for medical diagnosis => AI (Artificial Intelligence)
Face recognition using Siamese Networks => DL (Deep Learning)
Weather forecasting using linear regression => ML (Machine Learning)


P-3: Intro to colab and Numpy and Pytorch [5 Marks]

In [ ]:
import torch

# Generate a 5x5 random matrix
tensor = torch.rand(5, 5)

# PyTorch statistics
mean_pt = torch.mean(tensor)
std_pt = torch.std(tensor)
sum_pt = torch.sum(tensor)

print("PyTorch Tensor:\n", tensor)
print("Mean (PyTorch):", mean_pt.item())
print("Std Dev (PyTorch):", std_pt.item())
print("Sum (PyTorch):", sum_pt.item())

# Convert to NumPy
tensor_np = tensor.numpy()

# NumPy statistics
mean_np = np.mean(tensor_np)
std_np = np.std(tensor_np)
sum_np = np.sum(tensor_np)

print("\nConverted NumPy Array:\n", tensor_np)
print("Mean (NumPy):", mean_np)
print("Std Dev (NumPy):", std_np)
print("Sum (NumPy):", sum_np)


PyTorch Tensor:
 tensor([[0.0543, 0.4272, 0.2461, 0.7830, 0.0845],
        [0.6275, 0.2532, 0.5723, 0.2936, 0.7817],
        [0.0348, 0.8331, 0.3419, 0.3111, 0.9938],
        [0.9809, 0.7274, 0.7881, 0.6160, 0.8966],
        [0.3222, 0.8398, 0.0841, 0.5271, 0.2348]])
Mean (PyTorch): 0.5062121748924255
Std Dev (PyTorch): 0.3085147440433502
Sum (PyTorch): 12.655304908752441

Converted NumPy Array:
 [[0.05427259 0.42722774 0.24614966 0.78297967 0.084503  ]
 [0.6275311  0.25315708 0.5722626  0.29360133 0.78173476]
 [0.03478312 0.83310556 0.3418575  0.31106853 0.9938454 ]
 [0.9809262  0.7274476  0.788068   0.61601585 0.89661956]
 [0.32221347 0.8398062  0.08414376 0.5271376  0.23484743]]
Mean (NumPy): 0.5062122
Std Dev (NumPy): 0.30228153
Sum (NumPy): 12.655305
